// Micro-textos de INTERFAZ del kiosko (no son catálogo del tenant).
// El catálogo (servicios, categorías, ubicaciones, marca) viene de Supabase.
// Estos son los textos POR DEFECTO (respaldo): cada tenant puede sobrescribir
// los que quiera en la base (tenants.ui_textos), y el resto cae aquí.
// La resolución tenant + respaldo vive en uiText.tsx (UiTextProvider/useUiText).

// El idioma es un texto libre (ampliable), no fijo a 2 valores.
export type Lang = string;

export const DEFAULT_UI: Record<string, Record<string, string>> = {
  es: {
    concierge: "Concierge digital",
    hello: "Hola",
    tap: "Toca para empezar",
    listening: "Escuchando",
    explore: "¿Qué te apetece hacer?",
    exploreSub:
      "Tu concierge digital. Reserva, paga y disfruta — todo en un solo lugar.",
    attractDesc:
      "Tours, taxis, museos, divisa…\nUn único asistente para tu visita.",
    free: "Gratis",
    from: "desde",
    view: "Ver",
    poweredBy: "powered by",
    viewCart: "Ver carrito",
    cart: "Tu carrito",
    cartEmpty: "Tu carrito está vacío",
    total: "Total",
    pay: "Pagar",
    remove: "Quitar",
    back: "Volver",
    items: "artículos",
    checkoutTitle: "Pago seguro",
    paying: "Procesando el pago…",
    paid: "¡Pago completado!",
    paidDesc: "Gracias por tu compra. Recoge los detalles en el mostrador.",
    paymentError: "No se pudo iniciar el pago",
    tryAgain: "Reintentar",
    newOrder: "Nueva compra",
    deliveryTitle: "¿Cómo quieres tu comprobante?",
    deliverySub: "Escanea el QR o envíatelo. También puedes imprimirlo.",
    channelEmail: "Email",
    channelSms: "SMS",
    channelWhatsapp: "WhatsApp",
    channelPrint: "Imprimir",
    emailPlaceholder: "tucorreo@ejemplo.com",
    phonePlaceholder: "+34 600 000 000",
    send: "Enviar",
    sending: "Enviando…",
    sent: "¡Enviado!",
    deliveryError: "No se pudo enviar",
    scanQr: "Escanea para ver tu comprobante",
    openReceipt: "Abrir comprobante",
    empty: "No hay opciones disponibles aquí.",
    addToCart: "Añadir al carrito",
    added: "Añadido al carrito",
    book: "Reservar",
    duration: "Duración",
    options: "opciones",
    seeOptions: "Ver opciones",
    details: "Detalles",
    selectDate: "Selecciona una fecha",
    chooseDate: "Elige cuándo vas",
    passengers: "Pasajeros",
    perPerson: "por persona",
    dateRequired: "Selecciona primero una fecha",
    passengersRequired: "Añade al menos un pasajero",
    subtotal: "Subtotal",
    editItem: "Editar",
    dateLabel: "Fecha",
    today: "Hoy",
    soldOut: "Agotado",
    checkingAvailability: "Comprobando disponibilidad…",
    fewLeft: "Últimas plazas",
    seatsLeft: "plazas disponibles",
    maxSeats: "Has alcanzado el máximo de plazas para esta fecha.",
    about: "Sobre la experiencia",
    meetingPoint: "Punto de encuentro",
    howToUse: "Cómo usar tu billete",
    boltSubtitle: "Indica destino y teléfono. La recogida es siempre este hotel.",
    boltPhone: "Móvil del viajero",
    boltPhoneNationalPlaceholder: "Número sin prefijo",
    boltPhoneRequired: "Introduce un número de móvil válido",
    boltCountrySearch: "Buscar país",
    boltSelectCountry: "País",
    boltPickup: "Dirección de recogida",
    boltPickupLocked: "Fija",
    boltPickupEmpty: "Configura la dirección en el panel del kiosko",
    boltDropoff: "Destino",
    boltDropoffPlaceholder: "Aeropuerto, estación, dirección…",
    boltDropoffRequired: "Indica un destino",
    boltAddressLoading: "Buscando direcciones…",
    boltAddressEmpty: "No hay coincidencias. Sigue escribiendo.",
    boltAddressAttribution: "Callejero · Geolocalizador SCN (IDEE)",
    boltWhen: "Cuándo",
    boltRequestNow: "Pedir ahora",
    boltRequestNowSub: "Un conductor llegará lo antes posible",
    boltScheduled: "Programar",
    boltScheduledSub: "Entre 30 minutos y 90 días",
    boltExpenseNote: "Nota de gasto",
    boltDriverNote: "Nota al conductor",
    boltOptional: "opcional",
    boltContinue: "Continuar",
    boltMissingPickup: "Este kiosko no tiene dirección de recogida. Configúrala en Dispositivos del panel.",
    boltApiPending: "La reserva real con Bolt se activará cuando tengamos la API de Ride Booker.",
  },
  en: {
    concierge: "Digital concierge",
    hello: "Hola",
    tap: "Tap to start",
    listening: "Listening",
    explore: "What would you like to do?",
    exploreSub:
      "Your digital concierge. Book, pay and enjoy — all in one place.",
    attractDesc:
      "Tours, taxis, museums, currency…\nOne assistant for your whole visit.",
    free: "Free",
    from: "from",
    view: "View",
    poweredBy: "powered by",
    viewCart: "View cart",
    cart: "Your cart",
    cartEmpty: "Your cart is empty",
    total: "Total",
    pay: "Pay",
    remove: "Remove",
    back: "Back",
    items: "items",
    checkoutTitle: "Secure payment",
    paying: "Processing payment…",
    paid: "Payment complete!",
    paidDesc: "Thanks for your purchase. Collect the details at the desk.",
    paymentError: "Couldn't start the payment",
    tryAgain: "Try again",
    newOrder: "New order",
    deliveryTitle: "How would you like your receipt?",
    deliverySub: "Scan the QR or send it to yourself. You can also print it.",
    channelEmail: "Email",
    channelSms: "SMS",
    channelWhatsapp: "WhatsApp",
    channelPrint: "Print",
    emailPlaceholder: "you@example.com",
    phonePlaceholder: "+34 600 000 000",
    send: "Send",
    sending: "Sending…",
    sent: "Sent!",
    deliveryError: "Couldn't send",
    scanQr: "Scan to view your receipt",
    openReceipt: "Open receipt",
    empty: "No options available here.",
    addToCart: "Add to cart",
    added: "Added to cart",
    book: "Book now",
    duration: "Duration",
    options: "options",
    seeOptions: "See options",
    details: "Details",
    selectDate: "Select a date",
    chooseDate: "Choose when you're going",
    passengers: "Passengers",
    perPerson: "per person",
    dateRequired: "Please select a date first",
    passengersRequired: "Add at least one passenger",
    subtotal: "Subtotal",
    editItem: "Edit",
    dateLabel: "Date",
    today: "Today",
    soldOut: "Sold out",
    checkingAvailability: "Checking availability…",
    fewLeft: "Few spots left",
    seatsLeft: "seats available",
    maxSeats: "You've reached the maximum seats for this date.",
    about: "About the experience",
    meetingPoint: "Meeting point",
    howToUse: "How to use your ticket",
    boltSubtitle: "Enter destination and phone. Pickup is always this hotel.",
    boltPhone: "Rider mobile",
    boltPhoneNationalPlaceholder: "Number without country code",
    boltPhoneRequired: "Enter a valid mobile number",
    boltCountrySearch: "Search country",
    boltSelectCountry: "Country",
    boltPickup: "Pickup address",
    boltPickupLocked: "Fixed",
    boltPickupEmpty: "Set the address in the kiosk panel",
    boltDropoff: "Dropoff",
    boltDropoffPlaceholder: "Airport, station, address…",
    boltDropoffRequired: "Enter a destination",
    boltAddressLoading: "Searching addresses…",
    boltAddressEmpty: "No matches. Keep typing.",
    boltAddressAttribution: "Spain streets · SCN Geolocator (IDEE)",
    boltWhen: "When",
    boltRequestNow: "Request now",
    boltRequestNowSub: "A driver will arrive as soon as possible",
    boltScheduled: "Schedule",
    boltScheduledSub: "Between 30 minutes and 90 days",
    boltExpenseNote: "Expense note",
    boltDriverNote: "Note to driver",
    boltOptional: "optional",
    boltContinue: "Continue",
    boltMissingPickup: "This kiosk has no pickup address. Set it under Devices in the panel.",
    boltApiPending: "Live Bolt booking will turn on once we have the Ride Booker API.",
  },
};

// Mapa de idioma -> locale para formatear fechas. Respaldo: el propio código.
export const INTL_LOCALES: Record<string, string> = {
  es: "es-ES",
  en: "en-GB",
};
